### ISSUE TITLE
Consider moving top-level `lib/` dir into `pkg/`

### ISSUE THREAD

**Issue by dsimansk** [knative/client-pkg#68]
I'd remove the `lib/` top-level dir completely. Maybe move to `pkg/util/test` package or just `pkg/util.`

_Originally posted by @dsimansk in https://github.com/knative/client-pkg/pull/67#discussion_r1001592501_

**Comment by vyasgun** [comment]
Closed by https://github.com/knative/client-pkg/pull/67
